---
- name: Deploy to Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Create a deployment
      command: /root/kubectl apply -f /root/Deployment.yml

    - name: Create a service
      command: /root/kubectl apply -f /root/Service.yml
