kind: Service
apiVersion: v1
metadata:
  name: nijat-app
  labels:
    app: nijat-app
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30163
  selector:
    app: nijat-app
  type: LoadBalancer
